"""PDF report generation using ReportLab."""
import json
from io import BytesIO
from typing import Any
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from models import Scan, User


def build_scan_pdf(scan: Scan, user: User) -> BytesIO:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="WTI Scan Report")
    styles = getSampleStyleSheet()
    h = ParagraphStyle("h", parent=styles["Title"], textColor=colors.HexColor("#0ea5e9"))
    flow = []
    flow.append(Paragraph("Web Threat Intelligence — Scan Report", h))
    flow.append(Spacer(1,12))
    meta = [
        ["User", user.username],
        ["Email", user.email],
        ["Scan Type", scan.scan_type.upper()],
        ["Date", scan.created_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Verdict", scan.verdict],
        ["Risk Score", f"{scan.risk_score} / 100"],
    ]
    t = Table(meta, colWidths=[120, 360])
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(0,-1), colors.HexColor("#0f172a")),
        ("TEXTCOLOR",(0,0),(0,-1), colors.white),
        ("GRID",(0,0),(-1,-1),0.5,colors.grey),
        ("FONTSIZE",(0,0),(-1,-1),10),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("LEFTPADDING",(0,0),(-1,-1),8),("RIGHTPADDING",(0,0),(-1,-1),8),
        ("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6),
    ]))
    flow.append(t); flow.append(Spacer(1,16))
    flow.append(Paragraph("<b>Input</b>", styles["Heading3"]))
    flow.append(Paragraph((scan.input_text or "")[:2000].replace("<","&lt;"), styles["BodyText"]))
    flow.append(Spacer(1,10))
    flow.append(Paragraph("<b>Detection Reasons</b>", styles["Heading3"]))
    for r in (scan.reasons or "").split("\n"):
        if r.strip(): flow.append(Paragraph("• "+r.replace("<","&lt;"), styles["BodyText"]))
    flow.append(Spacer(1,10))
    flow.append(Paragraph("<b>Security Suggestions</b>", styles["Heading3"]))
    for r in (scan.suggestions or "").split("\n"):
        if r.strip(): flow.append(Paragraph("• "+r.replace("<","&lt;"), styles["BodyText"]))
    if scan.model_details:
        flow.append(Spacer(1,10))
        flow.append(Paragraph("<b>Algorithm Comparison</b>", styles["Heading3"]))
        try:
            algos = json.loads(scan.model_details)
            algo_rows = [["Algorithm", "Risk", "Verdict", "Confidence"]]
            for key, a in sorted(algos.items()):
                conf = f"{float(a['prob'])*100:.1f}%" if 'prob' in a else "-"
                algo_rows.append([a.get('label',key), f"{a.get('risk',0)}/100", a.get('verdict','-'), conf])
            at = Table(algo_rows, colWidths=[140, 80, 100, 100])
            at.setStyle(TableStyle([
                ("BACKGROUND",(0,0),(-1,0), colors.HexColor("#0ea5e9")),
                ("TEXTCOLOR",(0,0),(-1,0), colors.white),
                ("GRID",(0,0),(-1,-1),0.5,colors.grey),
                ("FONTSIZE",(0,0),(-1,-1),9),
                ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
                ("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),
                ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
            ]))
            flow.append(at)
        except Exception: pass
    if scan.description:
        flow.append(Spacer(1,10))
        flow.append(Paragraph("<b>Notes</b>", styles["Heading3"]))
        flow.append(Paragraph(scan.description.replace("<","&lt;"), styles["BodyText"]))
    flow.append(Spacer(1,18))
    flow.append(Paragraph("<font color='#64748b'>Generated by Web Threat Intelligence System</font>", styles["BodyText"]))
    doc.build(flow)
    buf.seek(0); return buf
